### ISSUE TITLE
왜 블로그 시작안하시나용?

### ISSUE THREAD

**Issue by youngjinmo** [dahyezz/dahyezz.github.io#1]
레포만 만들고 왜 블로그는 시작안하니 ㅋㅋㅋㅋㅋ

**Comment by dahyezz** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ헐 지금봤네요ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 작년에 하려다 귀찮아서 놔두고,, 이제 다시 시작하려고요,,^^,, 잘 지내시져?ㅋㅋㅋㅋㅋ

**Comment by youngjinmo** [comment]
나는 요즘 면접보러 다니느라 바쁘다...ㅋㅋㅋ
넌 잘지내니ㅋㅋㅋ

**Comment by dahyezz** [comment]
ㅋㅋ저도 뭐.. 작년회사 퇴사하고 올해 다시 취업했는데 웹 개발쪽이 아니고 db 보안쪽이라 적응중이져,, 퇴사하신건가요ㅋㅋ

**Comment by youngjinmo** [comment]
올해 초 퇴사하고 공부하다가 이제야 면접다니는중 ㅋㅋ 이번에 서비스쪽으로 가보려고 노력중인데 쉽지않넹 후..ㅋㅋㅋ
그나저나 블로그 언제개설해 그래섴ㅋㅋㅋㅋ

**Comment by dahyezz** [comment]
zzzㅋㅋㅋㅋㅋㅋㅋㅋ면접 ㅠㅠ 힘들져.. 화이팅..ㅠㅠ
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ이제 해야죠,,ㅋ,ㅋㅋㅋㅋㅋㅋㅋㅋ 주말에,,할겁ㄴ디ㅏ,,^^,,
